### ISSUE TITLE
Erro em Print

### ISSUE THREAD

**Issue by Marciobroficial** [tchfer/PYTHON#2]
Fernando seu exercício contem um erro em um dos print.
No caso exer.16.
Mandei esse isseus para server de treino da aula de GitHab.

**Comment by tchfer** [comment]
Dependendo do fuso horário que a máquina ou plataforma pega, ele muda
mesmo. Foi por isso que te enviei o código para checar para mim.

Mandei mensagem para a professora. Vamos ver o que ela fala
